version: '3.6'

# 官网：https://drone.io/
# 部署：docker stack deploy --compose-file=drone-stack.yml drone

# 生成Drone通信RPC_SECRET
# openssl rand -hex 16
# 94fac34927b1fdbe184bd647f8229263

services:
  drone:
    image: drone/drone:1
    environment:
      - TZ=Asia/Shanghai
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GOGS_SERVER=http://172.17.193.184:3000
      - DRONE_RPC_SECRET=94fac34927b1fdbe184bd647f8229263
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=172.17.193.184:3080
    networks:
      - stack
    volumes:
      - data:/data
    ports:
      - "3080:80"
      - "3443:443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==node2
  runner:
    image: drone/drone-runner-docker:1
    environment:
      - TZ=Asia/Shanghai
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET=94fac34927b1fdbe184bd647f8229263
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
    networks:
      - stack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1

networks:
  stack:
    driver: overlay
    attachable: true

volumes:
  data:

