version: '3.6'

# MicroService Deploy API
# docker stack deploy -c micro-stack.yml micro

services:
  # 配置中心
  config:
    image: "mszs/config:1.0.0"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  # 服务网关
  gateway:
    image: "mszs/gateway:1.0.0"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
    depends_on: [config]
  # 短信服务
  # 邮件服务
  # 验证码服务
  # 会员服务
  # 机构服务
  # 储值账户
  # 积分账户
  # 收银服务
  # 电子卡券

networks:
  stack:
    driver: overlay
    attachable: true

