version: '3.6'

# 业务服务部署
services:
  config:
    image: "mszs/config:1.0.0"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  gateway:
    image: "mszs/gateway:1.0.0"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
    depends_on: [config]
  member:
    image: "mszs/member:1.0.0"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
    depends_on: [config]

networks:
  stack:
    driver: overlay
    attachable: true

