version: '3.6'

services:
  nginx:
    image: nginx:1.14.0-alpine
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    networks:
      - ms
    volumes:
      - nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - nginx/conf/conf.d/:/etc/nginx/conf.d/
      - nginx/ssl/:/etc/nginx/ssl/
      - nginx/logs/:/var/log/nginx/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 30s
        max_failure_ratio: 0.1
        order: start-first
    # 运行节点限制条件
    constraints:
      - 'node.labels.nginx == 1'

networks:
  ms:
    external: true
