version: '3.6'
services:
  proxy:
    image: "nginx:1.17-alpine"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "39480:80"
      - "39443:443"
    networks:
      - cluster
    #volumes:
      #- nginx/nginx.conf:/etc/nginx/nginx.conf
      #- nginx/conf.d/:/etc/nginx/conf.d/
      #- nginx/ssl/:/etc/nginx/ssl/
      #- nginx/logs/:/var/log/nginx/
      #- nginx/html/:/usr/share/nginx/html/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 30s
        max_failure_ratio: 0.1
        order: start-first
      # 运行节点限制条件。创建标签：
      placement:
        constraints:
          - 'node.labels.nginx==1'

networks:
  cluster:
    external: true
