version: '3.6'

# 官网：https://drone.io/
# 文档：https://docs.drone.io/
# 插件：http://plugins.drone.io
# 部署：docker stack deploy --compose-file=drone-stack.yml drone

# 生成Drone通信RPC_SECRET
# openssl rand -hex 16
# 94fac34927b1fdbe184bd647f8229263

services:
  # Drone Server
  drone:
    image: drone/drone:1
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GOGS_SERVER=http://git.umq.cn
      - DRONE_RPC_SECRET=94fac34927b1fdbe184bd647f8229263
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=192.168.200.112:3080
      - DRONE_USER_CREATE=username:zengs,admin:true
    networks:
      - stack
    volumes:
      - data:/data
    ports:
      - "3080:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==localhost.node112
  # Drone Runner
  runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET=94fac34927b1fdbe184bd647f8229263
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
    networks:
      - stack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1

networks:
  stack:
    driver: overlay
    attachable: true

volumes:
  data:



# Drone Cli
# export DRONE_SERVER=http://drone
# export DRONE_TOKEN=UXsqjDqcoyooDtk9mc1qvZfUEerL4P2E
# drone info
# docker run --network drone_stack -e DRONE_SERVER=http://drone -e DRONE_TOKEN=k72FHEmf3e30IJd70Yg7vcLAQYVmCMNU --rm -it drone/cli info
# docker run --network drone_stack -e DRONE_SERVER=http://drone -e DRONE_TOKEN=k72FHEmf3e30IJd70Yg7vcLAQYVmCMNU --rm -it drone/cli orgsecret add zengs sshhost 192.168.200.112
# docker run --network drone_stack -e DRONE_SERVER=http://drone -e DRONE_TOKEN=k72FHEmf3e30IJd70Yg7vcLAQYVmCMNU --rm -it drone/cli orgsecret add zengs sshport 22
# docker run --network drone_stack -e DRONE_SERVER=http://drone -e DRONE_TOKEN=k72FHEmf3e30IJd70Yg7vcLAQYVmCMNU --rm -it drone/cli orgsecret add zengs sshname root
# docker run --network drone_stack -e DRONE_SERVER=http://drone -e DRONE_TOKEN=k72FHEmf3e30IJd70Yg7vcLAQYVmCMNU --rm -it drone/cli orgsecret add zengs sshpass root
