version: '3.6'

# MicroService Deploy API
# docker stack deploy -c micro-stack.yml micro

services:
  # HTTP代理，通过代理访问子网服务
  proxy:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/proxy:latest"
    networks: [stack]
    ports:
      - "39084:39084"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 验证码服务
  config:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/config:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    command:
      - /config --mongo=mongodb://unionlive:unionlive@192.168.200.112:27017/unionlive?authSource=admin&authMechanism=SCRAM-SHA-1
  # 验证码服务
  gateway:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/gateway:latest"
    networks: [stack]
    ports:
      - "39701:80"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 验证码服务
  captcha:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/captcha:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 会员服务
  member:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/member:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 机构服务
  org:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/org:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 商城服务
  mall:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/mall:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 订单服务
  order:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/order:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 现金账户
  cash:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/cash:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 短信服务
  sms:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/sms:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  # 邮件服务
  email:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/email:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

networks:
  stack:
    driver: overlay
    attachable: true

