version: '3.6'

# MicroService Deploy API
# docker stack deploy -c micro-stack.yml micro

services:
  # HTTP代理
  proxy:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/proxy:latest"
    networks: [stack]
    ports:
      - "39084:39084"
    deploy:
      mode: replicated
      replicas: 1
  # 验证码服务
  gateway:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/gateway:latest"
    networks: [stack]
    ports:
      - "39701:80"
    deploy:
      mode: replicated
      replicas: 1
  # 验证码服务
  captcha:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/captcha:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  # 会员服务
  member:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/member:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  # 商城服务
  mall:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/mall:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  # 订单服务
  order:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/order:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  # 现金账户
  cash:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/cash:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  # 短信服务
  sms:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/sms:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1
  # 邮件服务
  email:
    image: "registry.cn-hangzhou.aliyuncs.com/mszs/email:latest"
    networks: [stack]
    deploy:
      mode: replicated
      replicas: 1

  # 短信服务
  # 邮件服务
  # 验证码服务
  # 会员服务
  # 机构服务
  # 储值账户
  # 积分账户
  # 收银服务
  # 电子卡券

networks:
  stack:
    driver: overlay
    attachable: true

